version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  spotinfinity-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080